# Workflow to build and run tests
name: Unit tests

on:
  # Runs on pushes targeting any branch if they modify any specified path
  push:
    paths:
      - "src/**"
      - "multinest/**"
      - "**.f90"
      - "tests/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FC: gfortran
  CC: gcc
  CXX: g++
  FFLAGS: -w -O3 -ffree-line-length-none
  CFLAGS: -I. -O3
  CXFLAGS: -I. -O3
  LIBS: -llapack -lcfitsio

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: liblapack-dev libcfitsio-dev
          version: 1.0
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build tests
        run: make test FC=gfortran CC=gcc CXX=g++ FFLAGS="-w -O3 -ffree-line-length-none" CFLAGS="-I. -O3" CXFLAGS="-I. -O3" LIBS="-llapack -lcfitsio"

      - name: Run unit tests
        run: ./bin/BayesX-tests 

